version: "3.9"
services:
  server:
    build:
      context: ./server
    image: server:latest
    container_name: server 
    ports:
      - "4242:4242"
    # depends_on:
    #   - redis
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379

  client: #Use this for a single client test
    build:
      context: ./client
    image: client:latest
    container_name: client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=4242

  client2: #Remove to test for a single client
    build:
      context: ./client
    image: client2:latest
    container_name: client2
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=4242

  client3: #Remove to test for a single client
    build:
      context: ./client
    image: client3:latest
    container_name: client3
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=4242

  # redis: #Use for caching service
  #   image: redis:7.2
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
